# Generated by Django 5.1.1 on 2025-08-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0044_chapter_chapter_updated_at_desc_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                ("recipient", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Award",
                "verbose_name_plural": "Awards",
                "ordering": ["-year", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="award",
            constraint=models.UniqueConstraint(
                fields=("name", "year", "recipient"), name="unique_award_year_recipient"
            ),
        ),
    ]
